show failed output for fetch command

diff --git a/gis b/gis
--- a/gis
+++ b/gis
@@ -49,7 +49,8 @@ function execute_git_command_on_list {
 
         # Execute 'fetch' or 'pull'
         if [ "$1" == "fetch" ]; then
-            git fetch --prune --all 1> /dev/null 2> >(trap 'kill $! 2> /dev/null' INT TERM; sed "s/^/${text_bold}${text_blue}${repository_name}${text_reset} /")
+            output=$(git fetch --prune --all --porcelain &> >(sed "s/^/${text_bold}${text_blue}${repository_name}${text_reset} /"))
+            [ "$?" != 0 ] && echo -e "${text_bold}${text_blue}${repository_name}${text_reset} ${text_bold}${text_red}ERROR${text_reset} while fetching\n${output}"
         elif [ "$1" == "pull" ]; then
             git pull --recurse-submodules > >(sed "s/^/${text_bold}${text_magenta}${repository_name}${text_reset} /")
         fi
